"""
tg_scraper.py — Telegram Channel Scraper Agent

Connects to Telegram as a user account (Telethon) and listens for
new messages in configured signal channels. Parses token signals,
saves them to tg_signals table, updates the Token table, and injects
candidates directly into the scanner pipeline.

Requires Railway env vars:
    TG_API_ID           — from https://my.telegram.org
    TG_API_HASH         — from https://my.telegram.org
    TG_SESSION_STRING   — generated by bot/scripts/generate_tg_session.py

Channel list is read from agent_params.tg_scraper_channels (comma-separated
channel usernames without @). Default: signalsolanaby4am

Confidence Engine integration:
    When Agent 5 scores a candidate, it checks for a recent TG signal
    on that mint. If found:
        - Base boost: +10 (tg_signal_confidence_boost param)
        - Volume boost: +5 if signal shows high volume
        - Clean dev: +5 if dev_pct == 0

Channel accuracy tracking:
    After paper trades close, the learning loop can call
    update_tg_channel_stats() to track how many signals from each
    channel actually resulted in wins vs losses.
"""

import asyncio
import logging
import os
import re
from datetime import datetime

logger = logging.getLogger(__name__)

# ── Config ───────────────────────────────────────────────────────────────────

TG_API_ID = os.getenv("TG_API_ID", "")
TG_API_HASH = os.getenv("TG_API_HASH", "")
TG_SESSION_STRING = os.getenv("TG_SESSION_STRING", "")

STARTUP_DELAY = 30  # seconds after bot start

# Solana address regex: base58, 32-44 chars
_CA_PATTERN = re.compile(r"[1-9A-HJ-NP-Za-km-z]{32,44}")

# Numeric value extractors
_NUM_PATTERNS = {
    "mcap": re.compile(
        r"(?:MC|Market\s*Cap|Mcap)[:\s]*\$?([\d,.]+)\s*([KkMmBb])?",
        re.IGNORECASE,
    ),
    "age": re.compile(
        r"(?:Age|Token\s*Age)[:\s]*([\d,.]+)\s*(s|sec|m|min|h|hr|d|day)?",
        re.IGNORECASE,
    ),
    "dev_pct": re.compile(
        r"(?:Dev|Dev\s*(?:Wallet|Hold|%))[:\s]*([\d,.]+)\s*%?",
        re.IGNORECASE,
    ),
    "holders": re.compile(
        r"(?:Holders?|Holder\s*Count)[:\s]*([\d,.]+)",
        re.IGNORECASE,
    ),
    "top10_pct": re.compile(
        r"(?:Top\s*10|Top10)[:\s]*([\d,.]+)\s*%?",
        re.IGNORECASE,
    ),
    "volume": re.compile(
        r"(?:Vol(?:ume)?(?:\s*24h)?)[:\s]*\$?([\d,.]+)\s*([KkMmBb])?",
        re.IGNORECASE,
    ),
    "liquidity": re.compile(
        r"(?:Liq(?:uidity)?|LP)[:\s]*\$?([\d,.]+)\s*([KkMmBb])?",
        re.IGNORECASE,
    ),
    "buy_count_m5": re.compile(
        r"(?:Buy(?:s)?(?:\s*M5|\s*5m)?)[:\s]*([\d,]+)",
        re.IGNORECASE,
    ),
    "sell_count_m5": re.compile(
        r"(?:Sell(?:s)?(?:\s*M5|\s*5m)?)[:\s]*([\d,]+)",
        re.IGNORECASE,
    ),
}

_PLATFORM_PATTERN = re.compile(
    r"(?:pump\.fun|pumpfun|bonk\.fun|bonkfun|bags|raydium|meteora)",
    re.IGNORECASE,
)

_MULTIPLIERS = {"k": 1_000, "m": 1_000_000, "b": 1_000_000_000}


def _parse_num(raw: str, suffix: str | None = None) -> float | None:
    """Parse a number string with optional K/M/B suffix."""
    try:
        val = float(raw.replace(",", ""))
        if suffix:
            val *= _MULTIPLIERS.get(suffix.lower(), 1)
        return val
    except (ValueError, TypeError):
        return None


def _parse_age_minutes(raw: str, unit: str | None = None) -> float | None:
    """Convert age string to minutes."""
    val = _parse_num(raw)
    if val is None:
        return None
    unit = (unit or "m").lower()
    if unit.startswith("s"):
        return val / 60
    if unit.startswith("h"):
        return val * 60
    if unit.startswith("d"):
        return val * 1440
    return val  # default minutes


def parse_signal_message(text: str) -> dict | None:
    """
    Parse a signal channel message and extract token data.
    Returns dict with extracted fields, or None if no valid CA found.
    """
    if not text:
        return None

    # Find Solana contract address
    cas = _CA_PATTERN.findall(text)
    if not cas:
        return None

    # Take the longest match (most likely to be a full address)
    mint = max(cas, key=len)
    if len(mint) < 32:
        return None

    result: dict = {"mint": mint}

    # Extract numeric fields
    for field, pattern in _NUM_PATTERNS.items():
        match = pattern.search(text)
        if match:
            groups = match.groups()
            raw = groups[0]
            suffix = groups[1] if len(groups) > 1 else None

            if field == "age":
                result[field] = _parse_age_minutes(raw, suffix)
            elif field in ("holders", "buy_count_m5", "sell_count_m5"):
                val = _parse_num(raw)
                result[field] = int(val) if val is not None else None
            else:
                result[field] = _parse_num(raw, suffix)

    # Platform detection
    plat_match = _PLATFORM_PATTERN.search(text)
    if plat_match:
        platform = plat_match.group(0).lower().replace(".", "").replace(" ", "")
        # Normalize
        if "pump" in platform:
            result["platform"] = "pump"
        elif "bonk" in platform:
            result["platform"] = "bonk"
        elif "bags" in platform:
            result["platform"] = "bags"
        else:
            result["platform"] = platform

    return result


# ── Main agent ───────────────────────────────────────────────────────────────

async def _handle_message(event, channel_name: str) -> None:
    """Process a single channel message."""
    from bot import state
    from database.models import (
        save_tg_signal, save_token, get_recent_tg_signal,
        log_agent_run, AsyncSessionLocal, select, Token,
    )

    text = event.message.text or event.message.message or ""
    if not text:
        return

    parsed = parse_signal_message(text)
    if not parsed or not parsed.get("mint"):
        return

    mint = parsed["mint"]
    logger.info(
        "TG signal [%s]: %s mcap=%s liq=%s dev=%s holders=%s",
        channel_name, mint[:12],
        parsed.get("mcap"), parsed.get("liquidity"),
        parsed.get("dev_pct"), parsed.get("holders"),
    )

    # Save signal to tg_signals table
    try:
        await save_tg_signal(
            mint=mint,
            channel=channel_name,
            mcap=parsed.get("mcap"),
            age_minutes=parsed.get("age"),
            dev_pct=parsed.get("dev_pct"),
            holders=parsed.get("holders"),
            top10_pct=parsed.get("top10_pct"),
            volume=parsed.get("volume"),
            liquidity=parsed.get("liquidity"),
            platform=parsed.get("platform"),
            buy_count_m5=parsed.get("buy_count_m5"),
            sell_count_m5=parsed.get("sell_count_m5"),
        )
    except Exception as exc:
        logger.warning("TG scraper: failed to save signal for %s: %s", mint[:12], exc)

    # Update Token table with extracted data
    try:
        async with AsyncSessionLocal() as session:
            tok = (await session.execute(
                select(Token).where(Token.mint == mint)
            )).scalar_one_or_none()

            if tok is None:
                # Create new token entry
                await save_token(
                    mint=mint,
                    name=None,
                    symbol=None,
                    price_usd=None,
                    market_cap=parsed.get("mcap"),
                    liquidity_usd=parsed.get("liquidity"),
                    volume_24h=parsed.get("volume"),
                    source="tg_signal",
                )
            else:
                # Update existing token with signal data
                if parsed.get("mcap") and (not tok.market_cap or parsed["mcap"] > 0):
                    tok.market_cap = parsed["mcap"]
                if parsed.get("liquidity"):
                    tok.liquidity_usd = parsed["liquidity"]
                if parsed.get("volume"):
                    tok.volume_24h = parsed["volume"]
                tok.last_updated_at = datetime.utcnow()
                await session.commit()
    except Exception as exc:
        logger.warning("TG scraper: failed to update token %s: %s", mint[:12], exc)

    # Check if we already have an open position on this token.
    # If yes, upgrade it to tg_signal rules (wider trail, longer grace).
    # If recently closed, DON'T re-inject — 24h cooldown applies.
    try:
        from database.models import (
            AsyncSessionLocal, PaperTrade, has_recent_close, get_param,
        )
        from sqlalchemy import select

        # tg_signal-specific re-entry cooldown — shorter than the 24h global
        # because 4am sometimes re-calls a winner. /setparam tg_signal_cooldown_hours.
        try:
            tg_cd = float(await get_param("tg_signal_cooldown_hours") or 4.0)
        except Exception:
            tg_cd = 4.0
        if await has_recent_close(mint, within_hours=tg_cd):
            logger.info("TG scraper: skip %s — already traded in last %.1fh", mint[:12], tg_cd)
            return

        async with AsyncSessionLocal() as session:
            # Admin (HQ) only — orphan subscriber relay rows must not block
            # HQ re-entry or 4am tg_signal upgrades.
            open_trade = (await session.execute(
                select(PaperTrade).where(
                    PaperTrade.token_address == mint,
                    PaperTrade.status == "open",
                    PaperTrade.subscriber_id.is_(None),
                )
            )).scalar_one_or_none()

            if open_trade:
                if "tg_signal" not in (open_trade.pattern_type or ""):
                    old_type = open_trade.pattern_type or ""
                    open_trade.pattern_type = f"tg_signal,{old_type}" if old_type else "tg_signal"
                    await session.commit()
                    logger.info(
                        "TG scraper: UPGRADED open trade %s to tg_signal rules",
                        (open_trade.token_name or mint[:12]),
                    )
                # Already have it open — don't inject as new candidate
                return
    except Exception as exc:
        logger.debug("TG scraper: upgrade check failed for %s: %s", mint[:12], exc)

    # FAST-PATH: open the trade DIRECTLY from tg_scraper instead of routing
    # through scanner. Cuts entry latency from ~3-8s to ~0.5-2s on 4am
    # signals — scanner round-trip was the bottleneck. Falls back to
    # candidate-injection if any step fails so scanner can retry.
    #
    # Diagnostic: every drop point logs WARNING with the explicit reason
    # so /4amreport untraded misses can be traced in Railway logs.
    fast_path_opened = False
    skip_reason = None
    try:
        from bot.scanner import fetch_token_data, parse_token_metrics
        from bot import state as _state
        from database.models import (
            open_paper_trade, get_params, compute_paper_balance,
        )

        pair = await fetch_token_data(mint, allow_any_dex=True, bypass_cache=True)
        if pair is None:
            skip_reason = "dexscreener_no_pair"
        else:
            metrics = parse_token_metrics(pair)
            entry_mc = metrics.get("market_cap", 0) or 0
            token_name = metrics.get("name", parsed.get("name") or mint[:12])

            if entry_mc <= 0:
                skip_reason = "dexscreener_zero_mc"
            else:
                tg_cfg = await get_params("paper_probe_size", "tg_signal_tp_x")
                tg_paper_sol = float(tg_cfg.get("paper_probe_size") or 0.2)
                tg_tp_x = float(tg_cfg.get("tg_signal_tp_x") or 8.0)

                bal = await compute_paper_balance(_state.PAPER_STARTING_BALANCE)
                if bal < tg_paper_sol + 0.05:
                    skip_reason = f"insufficient_balance({bal:.3f}<{tg_paper_sol + 0.05:.3f})"
                else:
                    pt = await open_paper_trade(
                        token_address=mint,
                        token_name=token_name,
                        entry_mc=entry_mc,
                        entry_price=entry_mc,
                        paper_sol=tg_paper_sol,
                        confidence=80.0,
                        pattern_type="tg_signal",
                        tp_x=tg_tp_x,
                        sl_pct=20.0,
                        trade_reasoning=f"AUTO-BUY [fast-path] from {channel_name}",
                    )
                    _state.paper_balance = await compute_paper_balance(_state.PAPER_STARTING_BALANCE)
                    _state.paper_trades_today += 1
                    fast_path_opened = True
                    logger.info(
                        "TG scraper FAST-PATH: opened %s at MC=%.0f | %.2f SOL | bal=%.4f",
                        token_name[:20], entry_mc, tg_paper_sol, _state.paper_balance,
                    )

                    # Relay to subscribers (background task — doesn't block)
                    try:
                        from bot.signal_relay import relay_trade_to_subscribers
                        await relay_trade_to_subscribers(
                            token_address=mint,
                            token_name=token_name,
                            entry_mc=entry_mc,
                            tp_x=tg_tp_x,
                            sl_pct=20.0,
                            pattern_type="tg_signal",
                            trade_reasoning=f"AUTO-BUY from {channel_name}",
                            confidence=80.0,
                        )
                    except Exception as exc:
                        logger.debug("Fast-path relay failed: %s", exc)
    except Exception as exc:
        logger.warning("TG scraper fast-path failed for %s: %s — falling back to scanner", mint[:12], exc)
        skip_reason = f"fast_path_exception:{type(exc).__name__}"

    # Log explicit skip reason so /4amreport untraded misses are
    # diagnosable. Visible in Railway under "TG scraper SKIPPED ...".
    if not fast_path_opened and skip_reason:
        logger.warning(
            "TG scraper SKIPPED %s — reason: %s",
            mint[:12], skip_reason,
        )

    # If fast-path opened the trade, skip the candidate injection.
    if fast_path_opened:
        return

    # FALLBACK: inject into scanner candidate pool. Scanner will pick up
    # via the urgent-wake event on next iteration. Used when fresh MC
    # fetch fails or any other fast-path step errors.
    candidate = {
        "mint": mint,
        "name": None,
        "symbol": None,
        "mcap": parsed.get("mcap"),
        "liquidity": parsed.get("liquidity"),
        "source": "tg_signal",
        "tg_channel": channel_name,
        "tg_dev_pct": parsed.get("dev_pct"),
        "tg_holders": parsed.get("holders"),
        "tg_top10_pct": parsed.get("top10_pct"),
        "tg_buy_count_m5": parsed.get("buy_count_m5"),
        "tg_volume": parsed.get("volume"),
    }

    # Add to pending candidates for the next scanner tick AND fire the
    # urgent-wake event so scanner processes this immediately instead of
    # waiting up to 15s for its next regular tick.
    state.pending_candidates.append(candidate)
    state.data_points_today += 1
    try:
        state.get_urgent_event().set()
    except Exception:
        pass

    logger.info("TG scraper: injected %s into scanner pipeline from [%s] (urgent wake)", mint[:12], channel_name)


async def tg_scraper_loop() -> None:
    """
    Main loop — connects to Telegram and listens for messages
    in configured signal channels.
    """
    if not TG_SESSION_STRING:
        logger.info("TG scraper: TG_SESSION_STRING not set — skipping")
        return

    if not TG_API_ID or not TG_API_HASH:
        logger.warning("TG scraper: TG_API_ID or TG_API_HASH not set — skipping")
        return

    await asyncio.sleep(STARTUP_DELAY)

    try:
        from telethon import TelegramClient, events
        from telethon.sessions import StringSession
    except ImportError:
        logger.error("TG scraper: Telethon not installed — add 'telethon' to requirements.txt")
        return

    # Channel list from env var (comma-separated usernames without @)
    channels_raw = os.getenv("TG_SCRAPER_CHANNELS", "signalsolanaby4am")
    channel_names = [c.strip().lstrip("@") for c in channels_raw.split(",") if c.strip()]

    if not channel_names:
        logger.info("TG scraper: no channels configured — skipping")
        return

    logger.info("TG scraper: connecting to Telegram (channels: %s)", ", ".join(channel_names))

    client = TelegramClient(
        StringSession(TG_SESSION_STRING),
        int(TG_API_ID),
        TG_API_HASH,
    )

    try:
        await client.start()
        logger.info("TG scraper: connected to Telegram")
    except Exception as exc:
        logger.error("TG scraper: failed to connect: %s", exc)
        return

    # Resolve channel entities
    channel_entities = []
    for name in channel_names:
        try:
            entity = await client.get_entity(name)
            channel_entities.append((entity, name))
            logger.info("TG scraper: listening to channel [%s] (id=%s)", name, entity.id)
        except Exception as exc:
            logger.warning("TG scraper: failed to resolve channel '%s': %s", name, exc)

    if not channel_entities:
        logger.warning("TG scraper: no channels resolved — disconnecting")
        await client.disconnect()
        return

    # Register event handler for new messages
    channel_ids = [e.id for e, _ in channel_entities]
    channel_id_to_name = {e.id: n for e, n in channel_entities}

    @client.on(events.NewMessage(chats=channel_ids))
    async def handler(event):
        chat_id = event.chat_id
        channel_name = channel_id_to_name.get(chat_id, "unknown")
        try:
            await _handle_message(event, channel_name)
        except Exception as exc:
            logger.error("TG scraper: message handler error [%s]: %s", channel_name, exc)

    from database.models import log_agent_run
    await log_agent_run(
        "tg_scraper", tokens_found=0, tokens_saved=0,
        notes=f"listening to {len(channel_entities)} channel(s): {', '.join(channel_names)}",
    )

    logger.info("TG scraper: agent started — listening for signals in %d channel(s)", len(channel_entities))

    # Keep running until disconnected
    try:
        await client.run_until_disconnected()
    except Exception as exc:
        logger.error("TG scraper: disconnected: %s", exc)
    finally:
        try:
            await client.disconnect()
        except Exception:
            pass
